### ISSUE TITLE
outbound networking

### ISSUE THREAD

**Issue by fimbault** [deislabs/wagi#14]
Nice project.

Wondering about "In the future, as WASI matures, we will relax the restrictions on outbound networking."

Could you explain what this implies? Thxs.

**Comment by technosophos** [comment]
Sure! Currently WASI does not have networking support in the standard. It is coming in the future, and there are a few people in DeisLabs working to get this support in. When I was writing WAGI, @radu-matei was working on a POC network library.

He blogged about it in depth here: https://radu-matei.com/blog/towards-sockets-networking-wasi/

I had been pondering adding support for that to WAGI, but we decided we'd wait until WASI provided a little more guidance on where we were going

There are a few possible outcomes right now:

- WASI may add an HTTP client request, in which case we will get a high-level HTTP client
- WASI may add a Berkeley-style networking stack, in which case we'll get full networking
- WASI may add a slimmed down (perhaps client only) networking implementation, and we'll have to see what that looks like

In the near term, it's sort of a hindrance on WAGI because we can't currently make outgoing network connections. But hopefully that will only be the case for a little while.

**Comment by radu-matei** [comment]
There are a few moving parts when talking about the networking libraries in WASI:

- the APIs (defined at the WASI spec layer)
- implementations of those APIs (in Wasm runtimes)
- language standard libraries that use the API (for example using Rust `TcpStream` from WebAssembly modules)

If we were to add the networking support as described in the article from the previous comment, we would essentially have to fork all three components described above, which means that when WASI adds networking support, modules written for WAGI will not be compatible with upstream WASI. On top of that, when WAGI ends up updating WASI, modules previously written for WAGI that used our forked networking stack would stop working on WAGI, which is obviously not ideal.
(not to mention users trying to compile those modules would have to use forked toolchains of their compilers and standard libraries.)

That being said, we could go another route - add a clearly separate API layer for outbound requests and provide some external libraries that users can import in their projects and use to make requests (like a Rust crate, or an NPM module for AssemblyScript).
This way, we could continue to support both our API layer and eventually the official WASI support without breaking anything, and would not require people to fork toolchains to compile things - but with the downside of  having to use external libraries to make outbound requests.

To be clear, I'm not suggesting we implement either of the two, I'm just listing the available options in WAGI until WASI adds upstream support for networking.

**Comment by technosophos** [comment]
Update: We are working on outbound HTTP.
