### ISSUE TITLE
pool processes?

### ISSUE THREAD

**Issue by dazinator** [deislabs/wagi#188]
When writing dotnet web api's I find I typically rely on out of the box performance features that only yield value within long running processes - such as:-
- in memory caches
- database connection pooling

I won't pretend to understand wasm or its runtime - my question is will wagi do the equivalent of start and kill my "process" for each http request (as is the traditional CGI model) then this will make it very challenging to adopt as its too big of a tradeoff e.g losing caches and connection pools etc) for most teams to fell comfortable with - as not many prefer willingly stepping back in the performance department imho except for perhaps in some niche scenarios.

I believe FastCGI solved this by pooling processes. Is this something this project would cater for? I think this would make it significantly more viable if it did.

**Comment by itowlson** [comment]
A WAGI server is a single process.  It launches a Wasm module for each request.  That Wasm module executes within the same process as the server (but in an isolated memory and execution space provided by the Wasm runtime).  So yes, it does do the equivalent of starting and killing on each request _but_ the things that it is starting and killing are extremely lightweight rather than full OS processes.

This WAGI implementation is no longer very active, though.  The original authors are no longer with Deis Labs, but have reimplemented WAGI alongside a more modern model in Spin (https://github.com/fermyon/spin).  Deis Labs have related projects in SpiderLightning (https://github.com/deislabs/spiderlightning/) and through Kubernetes (https://github.com/containerd/runwasi), but I'm not qualified to explain them (I'm one of the old Deis Labs folks, who worked on WAGI but is now on Spin).

Hope this makes sense - I'm happy to follow up if you're interested in doing more with the WAGI model or with this repo, but projects such as Spin and Slight are where the work is now happening.

**Comment by dazinator** [comment]
@itowlson - thank you very much for the explanation. I came accross the wagi project via a recent YouTube vid: https://m.youtube.com/watch?v=97yJtD5FKe4 - I suspect the author of that vid may not have known, I will checkout those other projects.

Fyi - the startup / teardown may be lightweight but if memory is not preserved for apps between requests then the perf ramifications of apps losing things like in memory caches and connection / object pools I suspect is still going to be an issue for many apps. It would be nice if there was an option for the WASM module to be cached / long lived - for re-use so apps can benefit from preserving memory between requests. I'll checkout those other projects to see if any offer this feature!
