### ISSUE TITLE
Remove Virtual Hosting

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#58]
Early on, we write Wagi to do multi-tenant hosting. So we had a number of features like virtual hosting that were designed to be strict and to reduce the possibility of accidentally loading the wrong site (information disclosure).

But our use case is rapidly evolving toward using a single Wagi instance per app. And in this case, it makes more sense to delegate the host mapping to Nomad or other services, and not have to explicitly configure a Wagi app. Rather, only Wagi itself would know about the host name, and that information would be supplied once for all endpoints hosted on that Wagi instance.

Should we remove virtual hosting, disallowing modules from declaring their own `host` name?

👍 = Yes
👎  = No

**Comment by thomastaylor312** [comment]
I think this is a good way to go for now. We can always add it back in later if we were wrong for some reason

**Comment by adamreese** [comment]
I agree with removing the `host` filter.  If it's needed at some point in the future the default should be to allow all hosts.

**Comment by itowlson** [comment]
Obviously this _could_ be useful for some scenarios.  For example, imagine an application with both a "productivity" interface and an "admin" interface.  The developer might well want to package these in the same bindle.  But an operator might want to deploy the productivity interface on `office.example.com` and the admin interface on `admin.example.com`.  Without virtual hosting, that would (as far as I can tell) require the developer to repackage the app in two bindles.

However, that would require a significant redesign anyway.  The developer couldn't embed the host name `office.example.com` into the bindle, because they want to also sell the app to `example.com`'s fierce competitor, `foo.com`.  We can imagine solutions around bindle groups, external mapping layers in WAGI, or goodness knows what.  But we should not try to second-guess possible designs now, or rush a design when nothing needs it at the moment.

So this is a long-winded way of agreeing with Adam.  *grin*  We should remove the `host` filter, because if it needs to come back it will have to look very difference anyway.

**Comment by technosophos** [comment]
Closed by #72
